const CREATE_STORY = "CREATE_STORY";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
const FETCH_ALL_STORIES = "FETCH_ALL_STORIES";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

const CREATE = "CREATE";
const DELETE = "DELETE";
const FETCH_ALL = "FETCH_ALL";
const UPDATE = "UPDATE";

export {
  FETCH_ALL_STORIES,     // POSSIBLY DELETE?
  FETCH_ALL,
  CREATE_STORY,     // POSSIBLY DELETE?
  CREATE,
  UPDATE_STORY,     // POSSIBLY DELETE?
  UPDATE, 
  DELETE_STORY,     // POSSIBLY DELETE?
  DELETE,
  AUTHENTICATION,
  LOGOUT,
};